<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
<hr>
<div class="footer-dark">
    <footer>
        <div class="container1">
            <div class="row">
                <div class="col-sm-6 col-md-3 item">
                    <br>
                    
                    <h3>Services</h3>
                        <ul>
                            <li><a href="#">Web design</a></li>
                            <li><a href="#">Development</a></li>
                            <li><a href="#">Hosting</a></li>
                        </ul>
                    <br>
                 </div>
                <div class="col-md-6 item text">
                    <h3>Back End Developers</h3>
                        <p id="Footerp">The new generation of <strong>Web Developers</strong></p>
                </div>
                <a href="https://youtu.be/mZpZB0Ks3o0"><h3 id="YT">Link to our video</h3></a>
                <a href="login.php"><h3 id="LOGIN">Login</h3></a>
                 <a href="phpenhancements.php"><h3 id="phpenhancements">phpenhancements</h3></a>
            </div>
           
        </div>
    </footer>
</div>

    
</body>
</html>