<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <header>


        <nav>
            <img src="Images/BED3.png" class="logo">
        </nav>

        
  
                
<ul class="toplist">

<li id="Homebutton"> 
    <a href="index.php" Title="&nbsp;Home">&nbsp;Home&nbsp;</a>
</li>
<li id="Jobsbutton">
    <a href="jobs.php" Title="&nbsp;Jobs">&nbsp;Jobs&nbsp;</a>
</li>

<li id="Applybutton">
    <a href="apply.php" Title="&nbsp;Apply">&nbsp;Apply&nbsp;</a>
</li>
<li id="Aboutbutton">
    <a href="about.php" Title="&nbsp;About">&nbsp;About&nbsp;</a>
</li>
</ul>


</header>

    
</body>
</html>  
    <!-- <div class="çontainer" id="abc"> --> 
       